// <auto-generated />
using System;
using EFEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFEntity.Migrations
{
    [DbContext(typeof(TescDbContext))]
    [Migration("20200628122839_inti5")]
    partial class inti5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFEntity.Configer.major_change", b =>
                {
                    b.Property<int>("mch_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("change_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("new_salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("new_second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("new_third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mch_id");

                    b.ToTable("major_change");
                });

            modelBuilder.Entity("EFEntity.Tesc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tesc");
                });

            modelBuilder.Entity("EFEntity.config_file_first_kind", b =>
                {
                    b.Property<int>("ffk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("first_kind_salary_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_sale_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ffk_id");

                    b.ToTable("config_file_first_kind");
                });

            modelBuilder.Entity("EFEntity.config_file_second_kind", b =>
                {
                    b.Property<int>("fsk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("second_salary_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_sale_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fsk_id");

                    b.ToTable("config_file_second_kind");
                });

            modelBuilder.Entity("EFEntity.config_file_third_kind", b =>
                {
                    b.Property<int>("ftk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("third_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("third_kind_is_retail")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("third_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("third_kind_sale_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ftk_id");

                    b.ToTable("config_file_third_kind");
                });

            modelBuilder.Entity("EFEntity.config_major", b =>
                {
                    b.Property<int>("mak_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("major_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("test_amount")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.HasKey("mak_id");

                    b.ToTable("config_major");
                });

            modelBuilder.Entity("EFEntity.config_major_kind", b =>
                {
                    b.Property<int>("mfk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("mfk_id");

                    b.ToTable("config_major_kind");
                });

            modelBuilder.Entity("EFEntity.config_primary_key", b =>
                {
                    b.Property<int>("prk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("key_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primary_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primary_key_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primary_key_table")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("prk_id");

                    b.ToTable("config_primary_key");
                });

            modelBuilder.Entity("EFEntity.config_public_char", b =>
                {
                    b.Property<int>("pbc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attribute_kind")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("attribute_name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("pbc_id");

                    b.ToTable("config_public_char");
                });

            modelBuilder.Entity("EFEntity.config_question_first_kind", b =>
                {
                    b.Property<int>("qfk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("qfk_id");

                    b.ToTable("config_question_first_kind");
                });

            modelBuilder.Entity("EFEntity.config_question_second_kind", b =>
                {
                    b.Property<int>("qsk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("qsk_id");

                    b.ToTable("config_question_second_kind");
                });

            modelBuilder.Entity("EFEntity.engage_answer", b =>
                {
                    b.Property<int>("ans_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("answer_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exam_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_idcard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.Property<string>("major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("resume_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("test_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("total_point")
                        .HasColumnType("float");

                    b.Property<string>("use_time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ans_id");

                    b.ToTable("engage_answer");
                });

            modelBuilder.Entity("EFEntity.engage_answer_details", b =>
                {
                    b.Property<int>("and_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("answer_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subject_id")
                        .HasColumnType("int");

                    b.HasKey("and_id");

                    b.ToTable("engage_answer_details");
                });

            modelBuilder.Entity("EFEntity.engage_exam", b =>
                {
                    b.Property<int>("exa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("exam_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("limite_time")
                        .HasColumnType("int");

                    b.Property<string>("major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exa_id");

                    b.ToTable("engage_exam");
                });

            modelBuilder.Entity("EFEntity.engage_exam_details", b =>
                {
                    b.Property<int>("exd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("exam_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("question_amount")
                        .HasColumnType("int");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exd_id");

                    b.ToTable("engage_exam_details");
                });

            modelBuilder.Entity("EFEntity.engage_interview", b =>
                {
                    b.Property<int>("ein_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EQ_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IQ_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("foreign_language_degree")
                        .HasColumnType("int");

                    b.Property<string>("human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("interview_amount")
                        .HasColumnType("int");

                    b.Property<string>("interview_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("interview_status")
                        .HasColumnType("int");

                    b.Property<string>("multi_quality_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("native_language_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registe_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("response_speed_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("resume_id")
                        .HasColumnType("int");

                    b.HasKey("ein_id");

                    b.ToTable("engage_interview");
                });

            modelBuilder.Entity("EFEntity.engage_major_release", b =>
                {
                    b.Property<int>("mre_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("engage_required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("engage_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_amount")
                        .HasColumnType("int");

                    b.Property<string>("major_describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mre_id");

                    b.ToTable("engage_major_release");
                });

            modelBuilder.Entity("EFEntity.engage_resume", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attachment_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("demand_salary_standard")
                        .HasColumnType("float");

                    b.Property<string>("engage_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_age")
                        .HasColumnType("int");

                    b.Property<DateTime>("human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("human_birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_college")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_educated_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_educated_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("human_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_history_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_homephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_idcard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_specility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("interview_status")
                        .HasColumnType("int");

                    b.Property<string>("pass_checkComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pass_check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("pass_check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("pass_checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass_passComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pass_regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("pass_register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recomandation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("test_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("test_check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("test_checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("total_points")
                        .HasColumnType("real");

                    b.HasKey("res_id");

                    b.ToTable("engage_resume");
                });

            modelBuilder.Entity("EFEntity.engage_subjects", b =>
                {
                    b.Property<int>("sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correct_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("derivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("key_a")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("key_b")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("key_c")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("key_d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("key_e")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sub_id");

                    b.ToTable("engage_subjects");
                });

            modelBuilder.Entity("EFEntity.human_file", b =>
                {
                    b.Property<int>("huf_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attachment_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bonus_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("delete_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("demand_salaray_sum")
                        .HasColumnType("float");

                    b.Property<int>("file_chang_amount")
                        .HasColumnType("int");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("human_birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_educated_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_educated_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("human_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_family_membership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_file_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_histroy_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_id_card")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_pro_designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_society_security_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hunma_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastly_change_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("major_change_amount")
                        .HasColumnType("int");

                    b.Property<double>("paid_salary_sum")
                        .HasColumnType("float");

                    b.Property<DateTime>("recovery_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("training_amount")
                        .HasColumnType("int");

                    b.Property<int>("vhuman_age")
                        .HasColumnType("int");

                    b.HasKey("huf_id");

                    b.ToTable("human_file");
                });

            modelBuilder.Entity("EFEntity.human_file_dig", b =>
                {
                    b.Property<int>("hfd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attachment_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bonus_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("delete_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("demand_salaray_sum")
                        .HasColumnType("float");

                    b.Property<int>("file_chang_amount")
                        .HasColumnType("int");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_age")
                        .HasColumnType("int");

                    b.Property<string>("human_bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("human_birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_educated_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_educated_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("human_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_family_membership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_file_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_histroy_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_id_card")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_pro_designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_society_security_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hunma_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastly_change_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("major_change_amount")
                        .HasColumnType("int");

                    b.Property<double>("paid_salary_sum")
                        .HasColumnType("float");

                    b.Property<DateTime>("recovery_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("training_amount")
                        .HasColumnType("int");

                    b.HasKey("hfd_id");

                    b.ToTable("human_file_dig");
                });

            modelBuilder.Entity("EFEntity.salary_grant", b =>
                {
                    b.Property<int>("sgr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("human_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_grant_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_paid_sum")
                        .HasColumnType("float");

                    b.Property<string>("salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_standard_sum")
                        .HasColumnType("float");

                    b.Property<string>("second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sgr_id");

                    b.ToTable("salary_grant");
                });

            modelBuilder.Entity("EFEntity.salary_grant_details", b =>
                {
                    b.Property<int>("grd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("bouns_sum")
                        .HasColumnType("float");

                    b.Property<double>("deduct_sum")
                        .HasColumnType("float");

                    b.Property<string>("human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary_grant_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_paid_sum")
                        .HasColumnType("float");

                    b.Property<double>("salary_standard_sum")
                        .HasColumnType("float");

                    b.Property<double>("sale_sum")
                        .HasColumnType("float");

                    b.HasKey("grd_id");

                    b.ToTable("salary_grant_details");
                });

            modelBuilder.Entity("EFEntity.salary_standard", b =>
                {
                    b.Property<int>("ssd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("change_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("check_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ssd_id");

                    b.ToTable("salary_standard");
                });

            modelBuilder.Entity("EFEntity.salary_standard_details", b =>
                {
                    b.Property<int>("sdt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.Property<string>("standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sdt_id");

                    b.ToTable("salary_standard_details");
                });

            modelBuilder.Entity("EFEntity.training", b =>
                {
                    b.Property<int>("tra_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("checkstatus")
                        .HasColumnType("int");

                    b.Property<string>("human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("training_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("training_hour")
                        .HasColumnType("int");

                    b.Property<string>("training_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("training_time")
                        .HasColumnType("datetime2");

                    b.HasKey("tra_id");

                    b.ToTable("training");
                });

            modelBuilder.Entity("EFEntity.users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_true_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
